	tilepal 0, GRAY, TEXT, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, BROWN, BROWN, TEXT, GREEN, GREEN, GREEN
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, BROWN, BROWN, TEXT, TEXT, BROWN, BROWN, GRAY
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, BROWN, BROWN, BROWN, BROWN, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, BROWN, TEXT, TEXT, TEXT, GREEN, GREEN, GREEN, GREEN
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT

rept 16
	db $ff
endr

	tilepal 1, GRAY, BROWN, BROWN, RED, YELLOW, GREEN, BROWN, YELLOW
	tilepal 1, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
